### ISSUE TITLE
Fatal errors found in configuration

### ISSUE THREAD

**Issue by victorlap** [Tecnativa/docker-tcp-proxy#4]
Hey I wanted to use your image, but unfortunately got the following erros:

```
app_1  | INFO:root:Magic ready, executing now: /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:8] : unexpected character 'e' in 'timeout client'
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:9] : unexpected character 'e' in 'timeout client-fin'
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:10] : unexpected character 'e' in 'timeout connect'
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:11] : unexpected character 'e' in 'timeout server'
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:12] : unexpected character 'e' in 'timeout server-fin'
app_1  | [ALERT] 013/235213 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:13] : unexpected character 'e' in 'timeout tunnel'
app_1  | [ALERT] 013/235213 (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
app_1  | [ALERT] 013/235213 (1) : Fatal errors found in configuration.
**** exited with code 1
```

docker-compose.yml
```yml
version: "2.1"
services:
  app:
    image: tecnativa/tcp-proxy
    environment:
      LISTEN: ":80"
      TALK: "data.pdok.nl:443"
    restart: always
    networks:
      - web
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:****"
      - "traefik.port=80"

networks:
  web:
    external: true
```
