### ISSUE TITLE
Proxying SMTP Traffic

### ISSUE THREAD

**Issue by dunklesToast** [Tecnativa/docker-tcp-proxy#5]
So I am trying to set up an mail proxy. IMAP is working as expected but I am getting TLS errors while using smtp.

```
version: '3.4'
services:
    proxy:
        image: tecnativa/tcp-proxy
        container_name: proxy
        environment:
            LISTEN:
                mail.domain.tld:143
                mail.domain.tld:587
            TALK:
                mail.otherdomain.tld:143
                mail.otherdomain.tld:587
        restart: unless-stopped
        network_mode: host
```

I am not quite sure if I miss something. Do I need to use an SSL certificate for the SMTP Traffic? If so, can this be achieved with this container?
